### ISSUE TITLE
Create script to automate GitHub developer ranking & statistics

### ISSUE THREAD

**Issue by guylepage3** [guylepage3/guylepage3#2]
> **Last updated**: Apr 2, 2023

**Description**
Create script to automate GitHub developer ranking & statistics. See [#1568 comment](https://github.com/guylepage3/personal/issues/1568#issuecomment-1493359226).

**Tasks**
- [x] Define script requirements.
- [x] Define calculations.
- [x] Build script. https://codesandbox.io/s/working-ozimwt?file=/index.html:108-192
- [x] Test.

**Script requirements & calculations**
- [x] Score `userStats.score`
- [x] Score `userStats.score` change in descriptor
- [x] Score % `scorePercent`
  - [x] (`userStats.score` / 300,000)*100 = `scorePercent`
- [x] Ranking `userStats.level`
- [x] Ranking % change in descriptor `rankPercentChange`
  - [x] (`scoreRankPercent` * 100)-100 = `rankPercentChange`
- [x] Rank % `rankPercent`
  - [x] (`userStats.score` / 300,000)*100 = `rankPercent`
- [x] All-time stars `userStars`
  - [x] (`userStats.directStars` + `userStats.indirectStars`) = `userStars`
- [x] All-time commits `userStats.commits`
- [x] All-time PR's `userStats.pullRequests`
- [x] All-time issues `userStats.issues`
- [x] Contributed to `userStats.contributedTo`
- [x] GitHub followers `userStats.followers`
- [x] All-time commits breakdown
  - [x] Morning commits `morningCommits` — (4am – 9am)
    - [x] `30.78250863061 %` × `userStats.commits` = `morningCommits`
  - [x] Late morning commits `lateMorningCommits` — (9am – 2pm)
    - [x] `45.265493999671 %` × `userStats.commits` = `lateMorningCommits`
  - [x] Afternoon commits `afternoonCommits` — (2pm – 7pm)
    - [x] `21.477889199408 %` × `userStats.commits` = `afternoonCommits`
  - [x] Evening commits `eveningCommits` — (7pm – 4am)
    - [x] `2.4741081703107 %` × `userStats.commits` = `eveningCommits`

**Reference(s)**
- [devRanking.json](https://github.com/guylepage3/guylepage3/blob/main/devRanking.json).
- [mdn web docs — Working with JSON](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/JSON).
- [mdn web docs — JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify).
- [StackOverflow — Simplified way to add up integer values from a JSON [duplicate]](https://stackoverflow.com/questions/60760044/simplified-way-to-add-up-integer-values-from-a-json).
- [JavaScript Program to Add Two Numbers](https://www.programiz.com/javascript/examples/add-number).
- [Top 5 JavaScript Playgrounds](https://linuxhint.com/top-five-javascript-playgrounds/).
- [Glamour — Since discovering the ‘four quarters method’ of daily organisation, I've been happier, healthier and way more productive](https://www.glamourmagazine.co.uk/article/four-quarters-method).
- [Refinery29 — How TikTok’s Four Quarters Method Can Boost Your Productivity & Mental Health](https://www.refinery29.com/en-us/tik-tok-four-quarters-productivity-method).

**Comment by guylepage3** [comment]
**GitHub developer ranking & statistics**<br/>
[Awesome GitHub Stats data](https://github.com/guylepage3/guylepage3/blob/main/devRanking.json)

```text
Ranking                   S+    ███████████████████░░░░░░    75.94 %   (Ranked top 24.06 % of developers)
Score                227,805    ███████████████████░░░░░░    75.94 %   (227,805 / 300,000)

All-time stars       613,705    █████████████████████████   100.00 %   (Indirect & direct stars)
All-time commits      12,166    █████████████████████████   100.00 %
All-time PR's            374    █████████████████████████   100.00 %
All-time issues        1,568    █████████████████████████   100.00 %
Contributed to            76    █████████████████████████   100.00 %
GitHub followers         144    █████████████████████████   100.00 %

Morning        6,270 commits    █████████████░░░░░░░░░░░░    51.54 % 
Daytime        4,057 commits    ████████░░░░░░░░░░░░░░░░░    33.34 % 
Evening        1,698 commits    ███░░░░░░░░░░░░░░░░░░░░░░    13.96 % 
Night            141 commits    █░░░░░░░░░░░░░░░░░░░░░░░░     1.16 %
```

**Comment by guylepage3** [comment]
Done
