### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by guylepage3** [guylepage3/guylepage3#80]
> **Last updated**: Aug 12, 2023

**Description**
All projects should be strictly typed by using TypeScript as it produces better outcomes and ensures code is properly written.

**Tasks**
- [x] Install TypeScript.
- [x] Create `.ts` file.
- [x] Convert to TypeScript.
- [x] Run `npx tsc index.ts` to convert to JavaScript.

**Reference(s)**
- [x] [Download TypeScript](https://www.typescriptlang.org/download)
